### ISSUE TITLE
Obfuscated code

### ISSUE THREAD

**Issue by albertcp** [qeeqbox/raven#3]
Hello!

I am trying to adapt the code to work with my software solution and Javascript code is obfuscated.

Is there a way that you can upload the javascript without obfuscated?

Thank you in advance!

Best regards.

**Comment by feddgs** [comment]
Hi, 

This code is obfuscated, why? This project uses a lot of open source libs, taking advantage of the community work and effort, but author obfuscates the code in orther to keep the "open source" code closed. Also author is violating the terms of the BSD license applied to d3.js. Bad, very bad. If you don't want to share your code, at least respect used  dependencies licenses.

**Comment by giga-a** [comment]
@feddgs I removed your comment because you have no idea what are you talking about.

**Comment by giga-a** [comment]
Hey @albertcp, 

Sorry, I did not see your comment until now!

> I am trying to adapt the code to work with my software solution and Javascript code is obfuscated.

Glad that you are thinking of adopting the code. And, wait for the new update (This may take sometime, I'm waiting on my new automated system logic to be up and running otherwise it will keep do the same thing, I was able to push the metadata a few days ago and hopefully the code gets pushed without obfuscation)

> Is there a way that you can upload the javascript without obfuscated?

Yes, as I mentioned above!
